'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { RefreshCw, Play, FileText } from 'lucide-react';

interface Document {
  id: string;
  name: string;
  search_query: string;
  content: string;
  created_at: string;
  document_type_id: string;
  document_types: {
    name: string;
  };
}

export default function DocumentsPanel() {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchDocuments = async () => {
    setIsLoading(true);
    const res = await fetch('/api/documents');
    const data = await res.json();
    setDocuments(data);
    setIsLoading(false);
  };

  useEffect(() => {
    fetchDocuments();
  }, []);

  const triggerScrape = async (documentTypeId: string, name: string) => {
    const searchQuery = prompt("Enter research query for the AI to investigate:");
    if (!searchQuery || !documentTypeId) {
      alert('Please select a valid document type and provide a query.');
      return;
    }

    setIsLoading(true);
    try {
      const res = await fetch('/api/documents/scrape', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentTypeId,
          name: name || `Research: ${searchQuery.substring(0, 40)}...`,
          searchQuery
        }),
      });

      const result = await res.json();
      if (!res.ok) {
        alert(`Error: ${result.error || 'Failed to generate document'}`);
      } else {
        alert('Research started! Refreshing knowledge base...');
      }
    } catch (err) {
      alert('Failed to trigger research. Check console for details.');
      console.error(err);
    } finally {
      setIsLoading(false);
      fetchDocuments();
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold">Knowledge Base</h2>
          <p className="text-zinc-400">Documents generated by AI research</p>
        </div>
        <Button onClick={fetchDocuments} disabled={isLoading} variant="outline">
          <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      <div className="grid gap-4">
        {documents.length === 0 ? (
          <Card className="bg-zinc-900 p-12 text-center">
            <FileText className="w-12 h-12 mx-auto text-zinc-600 mb-4" />
            <p className="text-zinc-400">No documents yet.</p>
            <p className="text-sm text-zinc-500 mt-2">Go to the Types tab to create document types, then trigger research.</p>
          </Card>
        ) : (
          documents.map((doc) => (
            <Card key={doc.id} className="bg-zinc-900">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-lg">{doc.name}</CardTitle>
                    <p className="text-xs text-emerald-400 mt-1">
                      Type: {doc.document_types?.name || 'Unknown'}
                    </p>
                  </div>
                  <Button 
                    size="sm" 
                    variant="outline"
                    onClick={() => triggerScrape(doc.document_type_id || '', doc.name)}
                  >
                    <Play className="w-3 h-3 mr-1" />
                    Research Again
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-xs text-zinc-500 mb-2">Query: {doc.search_query}</div>
                <div className="max-h-60 overflow-auto bg-zinc-950 p-4 rounded border border-zinc-800 text-sm whitespace-pre-wrap font-light">
                  {doc.content}
                </div>
                <div className="text-[10px] text-zinc-500 mt-3">
                  Created: {new Date(doc.created_at).toLocaleString()}
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
