'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { RefreshCw, Play, FileText, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

interface Document {
  id: string;
  name: string;
  search_query: string;
  content: string;
  created_at: string;
  document_type_id: string;
  document_types: {
    name: string;
  };
}

export default function DocumentsPanel() {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchDocuments = async () => {
    setIsLoading(true);
    const { data, error } = await supabase
      .from('documents')
      .select(`
        *,
        document_type_id,
        document_types (
          name
        )
      `)
      .order('created_at', { ascending: false });

    if (data) setDocuments(data as any);
    if (error) console.error('Error fetching documents:', error);
    setIsLoading(false);
  };

  useEffect(() => {
    fetchDocuments();
  }, []);

  const handleDelete = async (id: string) => {
    if (!window.confirm('Are you sure you want to delete this document?')) return;

    const { error } = await supabase
      .from('documents')
      .delete()
      .eq('id', id);

    if (!error) {
      fetchDocuments();
    } else {
      console.error('Error deleting document:', error);
    }
  };

  const triggerScrape = async (documentTypeId: string, name: string) => {
    const searchQuery = prompt("Enter research query for the AI to investigate:");
    if (!searchQuery || !documentTypeId) {
      alert('Please select a valid document type and provide a query.');
      return;
    }

    setIsLoading(true);
    try {
      const res = await fetch('/api/documents/scrape', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentTypeId,
          name: name || `Research: ${searchQuery.substring(0, 40)}...`,
          searchQuery
        }),
      });

      const result = await res.json();
      if (!res.ok) {
        alert(`Error: ${result.error || 'Failed to generate document'}`);
      } else {
        alert('Research started! Refreshing knowledge base...');
      }
    } catch (err) {
      alert('Failed to trigger research. Check console for details.');
      console.error(err);
    } finally {
      setIsLoading(false);
      fetchDocuments();
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold text-foreground">Knowledge Base</h2>
          <p className="text-muted-foreground">Documents generated by AI research</p>
        </div>
        <Button onClick={fetchDocuments} disabled={isLoading} variant="outline" className="border-border hover:bg-muted">
          <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      <div className="grid gap-4">
        {documents.length === 0 ? (
          <Card className="p-12 text-center border border-border">
            <FileText className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
            <p className="text-foreground">No documents yet.</p>
            <p className="text-sm text-muted-foreground mt-3">Go to the Document Types tab to create types, then trigger research from here.</p>
          </Card>
        ) : (
          documents.map((doc) => (
            <Card key={doc.id} className="border border-border">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-lg">{doc.name}</CardTitle>
                    <p className="text-xs text-primary mt-1">
                      Type: {doc.document_types?.name || 'Unknown'}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => triggerScrape(doc.document_type_id || '', doc.name)}
                    >
                      <Play className="w-3 h-3 mr-1" />
                      Research Again
                    </Button>
                    <Button 
                      size="sm" 
                      variant="ghost" 
                      className="text-destructive"
                      onClick={() => handleDelete(doc.id)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-xs text-muted-foreground mb-2">Query: {doc.search_query}</div>
                <div className="max-h-60 overflow-auto bg-muted p-4 rounded border border-border text-sm whitespace-pre-wrap font-light text-foreground leading-relaxed">
                  {doc.content}
                </div>
                <div className="text-[10px] text-muted-foreground mt-3">
                  Created: {new Date(doc.created_at).toLocaleString()}
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
