-- Migration: 20260415114130_initial_schema.sql
-- Created: 2026-04-15
-- Description: Initial schema for Carbonchat as defined in SPECS.md
-- Uses pgcrypto + gen_random_uuid() (correct for Supabase)

-- Enable pgcrypto extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Document Types Table
-- Stores reusable transformation instruction templates
CREATE TABLE IF NOT EXISTS document_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  transformation_instructions TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Documents Table
-- Stores the actual knowledge generated by AI research
CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  document_type_id UUID NOT NULL REFERENCES document_types(id) ON DELETE CASCADE,
  search_query TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_documents_document_type_id ON documents(document_type_id);
CREATE INDEX IF NOT EXISTS idx_documents_created_at ON documents(created_at DESC);

-- Row Level Security
ALTER TABLE document_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public read access to document_types" ON document_types 
  FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Public read access to documents" ON documents 
  FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Authenticated users can manage document_types" ON document_types 
  FOR ALL TO authenticated USING (true);

CREATE POLICY "Authenticated users can manage documents" ON documents 
  FOR ALL TO authenticated USING (true);

-- Automatic updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_documents_updated_at 
  BEFORE UPDATE ON documents 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comments for clarity
COMMENT ON TABLE document_types IS 'Reusable templates containing transformation instructions for how AI should synthesize research into knowledge';
COMMENT ON TABLE documents IS 'Knowledge entries created by AI agents via internet research. Each document is linked to a document_type.';

-- Seed some useful default document types
INSERT INTO document_types (name, transformation_instructions, description) VALUES
('General Knowledge', 
 'Summarize the key facts, concepts, and insights from the research. Structure the response clearly with sections if appropriate. Focus on accuracy and usefulness for a general audience.',
 'General purpose knowledge synthesis'),
('Technical Documentation',
 'Extract technical details, specifications, code examples, architecture, and best practices. Structure as proper technical documentation with clear explanations, usage examples, and warnings where appropriate.',
 'For APIs, libraries, frameworks, tools, and technical subjects')
ON CONFLICT DO NOTHING;
